//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books_of_Attributes
    {
        public int ID { get; set; }
        public int AttributesID { get; set; }
        public int BooksID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual AttributValue AttributValue { get; set; }
    }
}
